### ISSUE TITLE
My issue

### ISSUE THREAD

**Issue by Proteev** [Zydratex/Gotcha#16]
when i open my gotcha 2.1v it says Unhandled Exception: System.TypeInitializationException: The type initializer for 'Gotcha_v2._1.Gotcha' threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'Nini, Version=1.1.0.0, Culture=neutral, PublicKeyToken=691faec150a7fa7b' or one of its dependencies. The system cannot find the file specified.
   at Gotcha_v2._1.Gotcha..cctor()
   --- End of inner exception stack trace ---
   at Gotcha_v2._1.Gotcha.Main(String[] args)
Idk what to do

**Comment by MiCROZi** [comment]
not sure why u opened the issue on this repo, but download the latest release [from here](https://github.com/OniSensei/Gotcha-v2.1)

**Comment by MiCROZi** [comment]
also remember to close this issue if you ever come back here lmao

**Comment by sivvy4402** [comment]
I paid $5 on the patreon, when will I get the program?

**Comment by MiCROZi** [comment]
Please be patient, oni (default) has been very busy lately, and he hasn't really been on Discord much since last week. He was in a car accident. It may take longer than usual, just remember to DM him on Discord (once)

Btw, this isn't the place for the new gotcha bot. Refer [here](https://github.com/OniSensei/Gotcha-v2.1)

**Comment by KingDarnit** [comment]
And for future reference, don't comment on another issue, instead either making a new issue or posting in our subreddit (r/gotchabot) would be easier to manage. You're lucky that I was subscribed to this repository and was checking emails

**Comment by sivvy4402** [comment]
Okay, I just can't dm him on discord because I'm waiting for him to accept the friend request.
Thank you though and I'm sorry for my rude behavior.
