### ISSUE TITLE
My iSsue, i have donated $1 and i cant even add you on discord. i cant autocatch

### ISSUE THREAD

**Issue by Chros87** [Zydratex/Gotcha#17]
System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\USER\Downloads\Gotcha-v2.1-2.1.1.2\Gotcha v2.1\bin\Debug\logs\211019015116_log.txt'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   at System.IO.StreamWriter..ctor(String path, Boolean append)
   at System.IO.File.AppendText(String path)
   at Gotcha_v2._1.Gotcha.Colorize(String msg) in C:\Users\D\source\repos\Gotcha v2.1\Gotcha v2.1\Gotcha.vb:line 1529
   at Gotcha_v2._1.gotchaLevel.levelFound(String msgDescription, String embedValue, String embedName) in C:\Users\D\source\repos\Gotcha v2.1\Gotcha v2.1\gotchaLevel.vb:line 18

**Comment by Chros87** [comment]
hello ? my email also does not have the link from paypal that i send you $1..

**Comment by Chros87** [comment]
Thanks its done
