### ISSUE TITLE
error when running 

### ISSUE THREAD

**Issue by Zadehl** [Zydratex/Gotcha#18]
Unhandled Exception: System.TypeInitializationException: The type initializer for 'Gotcha_v2._1.Gotcha' threw an exception. ---> System.InvalidCastException: Conversion from string "" to type 'Boolean' is not valid. ---> System.FormatException: Input string was not in a correct format.
   at Microsoft.VisualBasic.CompilerServices.Conversions.ParseDouble(String Value, NumberFormatInfo NumberFormat)
   at Microsoft.VisualBasic.CompilerServices.Conversions.ToBoolean(String Value)
   --- End of inner exception stack trace ---
   at Microsoft.VisualBasic.CompilerServices.Conversions.ToBoolean(String Value)
   at Gotcha_v2._1.Gotcha..cctor()
   --- End of inner exception stack trace ---
   at Gotcha_v2._1.Gotcha.Main(String[] args)

**Comment by MiCROZi** [comment]
dont. fucking. use. this.

you have eyes and a brain, please use them as intended.

**Comment by tushrpal** [comment]
![error](https://user-images.githubusercontent.com/62652414/77539169-f028b100-6ec6-11ea-817b-931b2b596982.png)
How can i fix these error
